networks:
  skynet:

services:
  mvc:
    build:
      context: Webflix/Webflix.MVC
      dockerfile: ../../.docker/mvc.dockerfile
    image: tangotew/mvcproject
    ports:
      - 5000:80
    networks:
      - skynet
  api:
    build:
      context: Webflix/Webflix.API
      dockerfile: ../../.docker/api.dockerfile
    image: tangotew/apiproject
    ports:
      - 4000:80
    networks:
      - skynet

version: "3.7"